apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: banking-system
  labels:
    app: customer-service
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://customer_user:customer_pass@customer-db:5432/customer_db"
