apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: banking-system
  labels:
    app: customer-service
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
